import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Voiting Game | Main Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 px-8 sm:px-20">
      <header className="text-center mb-12">
        <h1 className="text-4xl font-bold text-gray-800 mb-4">
          Welcome to the Voiting Game
        </h1>
        <p className="text-lg text-gray-600">
          Lots of funny jokes you can find here.
        </p>
      </header>
      <main>
        <Link
          href="/joke"
          className="px-6 py-3 text-lg bg-blue-500 text-white rounded shadow hover:bg-blue-600 transition"
        >
          Let is start
        </Link>
      </main>
      <footer className="mt-12 text-center text-gray-500">
        <p className="text-sm">© 2024 Created by Gordiienko</p>
      </footer>
    </div>
  );
}
